package com.psp.instapay.model.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing an account in the system.
 * Maps to the "account" table in the database.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "account")
public class Account {

    /**
     * The unique identifier for the account.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user associated with the account.
     * Represents a many-to-one relationship with the User entity.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The bank associated with the account.
     * Represents a many-to-one relationship with the Bank entity.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bank_id", nullable = false)
    private Bank bank;

    /**
     * The unique account number.
     * Limited to 16 characters and cannot be null.
     */
    @Column(name = "account_number", nullable = false, unique = true, length = 16)
    private String accountNumber;

    /**
     * The current balance of the account.
     * Defaults to 0.0 and cannot be null.
     */
    @Column(name = "balance", nullable = false)
    private Double balance = 0.0;

    /**
     * Constructor to create an account with the specified user, bank, and account number.
     *
     * @param user The user associated with the account.
     * @param bank The bank associated with the account.
     * @param accountNumber The unique account number.
     */
    public Account(User user, Bank bank, String accountNumber) {
        this.user = user;
        this.bank = bank;
        this.accountNumber = accountNumber;
    }
}