spring:
  application:
    name: instapay

  datasource:
    url: jdbc:mysql://localhost:3306/instapay_db
    username: pspuser
    password: psppassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.transaction: DEBUG

server:
  port: 8080

# JWT Configuration
jwt:
  secret: 400e3f4b5c6d7e8f9a0b1c2d3e4f5g6h7i8j9k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z56
  expiration: 3600 # in seconds

# Encryption Configuration
encryption:
  key: 1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p
